name: Test

on:
  push:
    branches: [master, develop, develop-*]
  pull_request_target:
    # The branches below must be a subset of the branches above
    branches: [master, develop, develop-*]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
      REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
      REACT_APP_SSO_CLIENT_ID: ${{ secrets.REACT_APP_SSO_CLIENT_ID }}
      REACT_APP_SSO_CLIENT_SECRET: ${{ secrets.REACT_APP_SSO_CLIENT_SECRET }}
      REACT_APP_ENDPOINT_URL: ${{ secrets.REACT_APP_ENDPOINT_URL }}
      REACT_APP_BI_ENDPOINT_URL: ${{ secrets.REACT_APP_BI_ENDPOINT_URL }}
      REACT_APP_ENCRYPT: ${{ secrets.REACT_APP_ENCRYPT }}
      REACT_APP_LICENSE: ${{ secrets.REACT_APP_LICENSE }}
      REACT_APP_TEST_MODE: ${{ secrets.REACT_APP_TEST_MODE }}
      REACT_APP_OAUTH_DEFAULT_USERNAME: ${{ secrets.REACT_APP_OAUTH_DEFAULT_USERNAME }}
      REACT_APP_OAUTH_DEFAULT_PASSWORD: ${{ secrets.REACT_APP_OAUTH_DEFAULT_PASSWORD }}
      REACT_APP_TEST_DOMAIN: ${{ secrets.REACT_APP_TEST_DOMAIN }}
      REACT_APP_TEST_EMAIL_RECEIVER: ${{ secrets.REACT_APP_TEST_EMAIL_RECEIVER }}
      REACT_APP_TEST_EMAIL_SENDER: ${{ secrets.REACT_APP_TEST_EMAIL_SENDER }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: yarn format:check

      - name: Run Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          CI=false yarn build

      - name: Run Test
        run: yarn test
